from .gcp_storage import NODE_CLASS_MAPPINGS
from .gcp_storage import NODE_DISPLAY_NAME_MAPPINGS

from .gcpVideoUploader import NODE_CLASS_MAPPINGS as VIDEO_NODE_CLASS_MAPPINGS
from .gcpVideoUploader import NODE_DISPLAY_NAME_MAPPINGS as VIDEO_NODE_DISPLAY_NAME_MAPPINGS

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
